name: Build JAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Package JAR
      run: ./gradlew jar

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: build/libs/*.jar
