name: Build EXE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Compile Java source files
      run: javac -d out $(find src -name "*.java")

    - name: Package JAR
      run: |
        mkdir -p build/libs
        jar cf build/libs/my-app.jar -C out .

    - name: Create EXE
      run: |
        jpackage --input build/libs --main-jar my-app.jar --name MyApp --type exe --dest build/exe

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: my-app-exe
        path: build/exe/MyApp.exe
