name: Build EXE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11 with jpackage
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install jpackage
      run: |
        choco install jdk11 --version=11.0.11 --source=https://community.chocolatey.org/api/v2/
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        refreshenv

    - name: Compile Java source files
      run: |
        $files = Get-ChildItem -Path src -Recurse -Filter *.java
        if ($files.Count -eq 0) { throw "No source files found" }
        javac -d out $files.FullName
      shell: pwsh

    - name: Package JAR
      run: |
        mkdir -p build/libs
        jar cf build/libs/my-app.jar -C out .

    - name: Create EXE
      run: |
        jpackage --input build/libs --main-jar my-app.jar --name MyApp --type msi --dest build/exe

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: my-app-exe
        path: build/exe/MyApp.msi
