name: Build JAR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Compile Java source files
      run: javac -d out src/**/*.java

    - name: Package JAR
      run: |
        mkdir -p build/libs
        jar cf build/libs/my-app.jar -C out .
    
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: build/libs/my-app.jar
